export const input_field_tasks = 'input.new-todo'
export const task_in_list = 'div.view'
export const button_complete_task = 'input.toggle:eq(1)'
export const complete_all_task = 'input.toggle'
export const button_clear_completed = 'button.clear-completed' 
export const input_edit_task = 'ul.todo-list > li' 
export const delete_button = '.destroy'
